repos:
  - repo: local
    hooks:
      - id: pytest
        name: Tests
        entry: poetry run pytest
        language: system
        pass_filenames: false
        always_run: true
      - id: black
        name: Black
        description: "Black: The uncompromising Python code formatter"
        entry: poetry run black
        args: [--line-length=100]
        language: system
        require_serial: true
        types: [python]
      - id: reorder-python-imports
        name: Reorder python imports
        description: "This hook reorders imports in python files."
        entry: poetry run reorder-python-imports
        language: system
        types: [python]
      - id: flake8
        name: Flake8
        description: "`flake8` is a command-line utility for enforcing style consistency across Python projects."
        entry: poetry run flake8
        args: [--max-line-length=100, --max-complexity=12]
        language: system
        require_serial: true
        types: [python]
      - id: check-poetry
        name: Poetry check
        description: Validates the structure of the pyproject.toml file
        entry: poetry check
        language: system
        pass_filenames: false
        files: pyproject.toml
